### ISSUE TITLE
Four spaces before equation syntax doesn't transform it to code block

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#211]
As you can see below, first should be as formula, but then code block as here in github. But i faced with double render formula

\begin{align}
\sigma^2 = \begin{pmatrix}
\sigma_1^2 & \sigma_{12} \\
\sigma_{12} & \sigma_2^2 
\end{pmatrix}.
\end{align}

    \begin{align}
        \sigma^2 = \begin{pmatrix}
        \sigma_1^2 & \sigma_{12} \\
        \sigma_{12} & \sigma_2^2 
        \end{pmatrix}.
    \end{align}

**Comment by OlgaRedozubova** [comment]
Hey @vladtimss.
Thank you.
This is expected behavior.
We have overridden [this rule](https://github.com/Mathpix/mathpix-markdown-it/blob/master/src/markdown/mdPluginRaw.ts#L905) for latent commands:

https://github.com/Mathpix/mathpix-markdown-it/blob/5ebd538421db4e7b82653c0d13f0cba63c9f8f6c/src/markdown/mdPluginRaw.ts#L816-L827 


Instead, you can use a block comment:
<img width="1271" alt="Screen Shot 2022-11-22 at 21 51 17" src="https://user-images.githubusercontent.com/32493105/203408255-28aa5ab1-2d68-410c-a712-7f17cbcd80c8.png">

**Comment by vladtimss** [comment]
Olga, thank you very much for your answer!

Did I understand correctly that I will not be able to achieve in the mathpix-markdown-it that I can make a section with code with 4 spaces? Like here - https://www.markdownguide.org/basic-syntax/#code-blocks-1

**Comment by OlgaRedozubova** [comment]
@vladtimss I've just updated [mathpix-markdown-it@1.0.80](https://www.npmjs.com/package/mathpix-markdown-it)

In new version I added `enableCodeBlockRuleToLatexCommands` parameter to use md Code block rule for LaTeX command 

**By default**:

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/32493105/204234620-6565b0f5-5cad-47f0-ac29-bc5dcd95d4a0.gif)


**enableCodeBlockRuleToLatexCommands = true**:

![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/32493105/204234984-b2675084-6be8-49ee-9f8f-8ffe4e884206.gif)
