### ISSUE TITLE
SyntaxError /node_modules/domino/lib/sloppy.js: 'with' in strict mode (10:4)

### ISSUE THREAD

**Issue by itssabhishek** [Mathpix/mathpix-markdown-it#222]
I tried using this library with the example provided in the documentation, but I received this error while running.

SyntaxError
/node_modules/domino/lib/sloppy.js: 'with' in strict mode (10:4)

   8 |   Window_run: function _run(code, file) {
   9 |     if (file) code += '\n//@ sourceURL=' + file;
 10 |     with(this) eval(code);
     |     ^
  11 |   },
  12 |   EventHandlerBuilder_build: function build() {
  13 |     try { 

I tried it on my local system as well, but the same error occurred.
Here's an example of an error.
![image](https://user-images.githubusercontent.com/68913813/211708671-aaee994a-0867-4c97-8d90-33bdf36f936f.png)

**Comment by zaiji100** [comment]
the same isuue with u, have u solved it.

**Comment by t3o-it** [comment]
Same here with vue and vite.

**Comment by holdehn** [comment]
same issue.

**Comment by OlgaRedozubova** [comment]
It was fixed in mathpix-markdown-it@1.2.4

https://codesandbox.io/s/interesting-stallman-2xxgng?file=/src/index.js

<img width="1233" alt="Screen Shot 2023-07-03 at 19 36 24" src="https://github.com/Mathpix/mathpix-markdown-it/assets/32493105/2bd22a8b-8857-440b-beed-0756ad87e4a9">
<img width="1219" alt="Screen Shot 2023-07-03 at 19 36 55" src="https://github.com/Mathpix/mathpix-markdown-it/assets/32493105/5b3e6a20-91c4-41d6-8442-c1d7e92a01a4">
<img width="1224" alt="Screen Shot 2023-07-03 at 19 37 07" src="https://github.com/Mathpix/mathpix-markdown-it/assets/32493105/92a32f47-df1e-49c7-b17a-c1c721ed0d08">
