### ISSUE TITLE
Using $$ and \begin syntax jointly

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#232]
Hi! Thanks for your work!

Could you give advise to solve the problem of jointly using two syntax - `$$ and \begin`

i try render this syntax
`$$ \begin{equation}
\left[
\begin{array}{ccc}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{array}
\right]
\end{equation}
 $$`

But get true render formula but with extra $$

Look at the screen
<img width="1423" alt="Снимок экрана 2023-03-01 в 12 29 56" src="https://user-images.githubusercontent.com/117174291/222099822-d3f30b1b-1b26-4502-8674-8dff8894c231.png">

**Comment by OlgaRedozubova** [comment]
> Hi! Thanks for your work!

Hi, @vladtimss. Thanks a lot.

> But get true render formula but with extra $$

This is because `\begin{equation}...\end{equation}` is already block math and doesn't require additional delimiter wrapping for block math.
Also block mathematics of the form:
`\begin{equation}...\end{equation}`
`\begin{align}...\end{align}`
`\begin{equation*}...\end{equation*}`
`\begin{align*}...\end{align*}`
`\begin{split}...\end{split}`
`\begin{gather}...\end{gather}`
`\begin{gather*}...\end{gather*}`
It does not require additional wrapping in separators for block math - this is already block math.

And the inline rule for `\begin{equation}...\end{equation}` has higher precedence than `$$..$$`
But if needed, you can use `\[..\]` instead of `$$..$$`


https://snip.mathpix.com/olga/notes/untitled-document-661-f524dbc1-29ff-4141-bf2a-69fafb4addcc

<img width="1302" alt="Screen Shot 2023-03-01 at 12 43 52" src="https://user-images.githubusercontent.com/32493105/222117142-dd1c3fc4-27d0-4a04-bc36-de3aa9230f4a.png">

**Comment by vladtimss** [comment]
@OlgaRedozubova many thanks!!!
