### ISSUE TITLE
Error applying strikethrough text using mathpix-markdown-it in web browsers.

### ISSUE THREAD

**Issue by lixumin-zai** [Mathpix/mathpix-markdown-it#353]
origin text: \underline{$\textcolor{red}{\sout{(-1,-\dfrac{\sqrt{3}}{3})\cup(\dfrac{\sqrt{3}}{3},1)}}$}

render in vscode: 
![image](https://github.com/user-attachments/assets/96b676e5-63fb-40c1-b72c-21dc472165aa)

but there is an error when  using the script "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.4/es5/bundle.js" to render it :
[TexConvert] ERROR=> {
  "message": "TeX error: Undefined control sequence \\sout",
  "latex": "\\textcolor{red}{\\sout{(-1,-\\dfrac{\\sqrt{3}}{3})\\cup(\\dfrac{\\sqrt{3}}{3},1)}}"
}

how to fix it 😭

**Comment by lixumin-zai** [comment]
Please help the adorable little turtle

**Comment by OlgaRedozubova** [comment]
@lixumin-zai  `\sout` is a text-mode command which is why MathJax does not implement it https://github.com/mathjax/MathJax/issues/819#issuecomment-42939918

You can use the enclose extension and do `\enclose{horizontalstrike}{...}` to strike-through an expression with a horizontal line.


```
\underline{$\textcolor{red}{\enclose{horizontalstrike}{(-1,-\dfrac{\sqrt{3}}{3})\cup(\dfrac{\sqrt{3}}{3},1)}}$}
```

<img width="1087" alt="Screenshot 2024-11-04 at 14 39 32" src="https://github.com/user-attachments/assets/46be3e9b-17f3-43f6-a243-fc28f583ff54">

**Comment by lixumin-zai** [comment]
The little turtle is very grateful to you.
